trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
printWidth: 120
arrowParens: 'avoid'
bracketSameLine: false
endOfLine: 'lf'
tailwindStylesheet: './src/styles/global.css'
plugins:
  - 'prettier-plugin-astro'
  - 'prettier-plugin-tailwindcss'
  - 'prettier-plugin-svelte'
overrides:
  - files: '*.astro'
    options:
      parser: 'astro'
      astroAllowShorthand: true
      jsxSingleQuote: true
  - files: '*.svelte'
    options:
      parser: 'svelte'
      svelteAllowShorthand: true
      jsxSingleQuote: true
  - files: '*.json'
    options:
      parser: 'json'
  - files: '*.md'
    options:
      parser: 'markdown'
  - files: '*.css'
    options:
      parser: 'css'
  - files: '*.xml.ts'
    options:
      singleQuote: false
