trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
printWidth: 80
arrowParens: 'avoid'
bracketSameLine: false
singleAttributePerLine: true
plugins:
  - 'prettier-plugin-astro'
overrides:
  - files: '*.astro'
    options:
      parser: 'astro'
      astroAllowShorthand: true
      jsxSingleQuote: true
  - files: '*.json'
    options:
      parser: 'json'
  - files: '*.md'
    options:
      parser: 'markdown'
  - files: '*.css'
    options:
      parser: 'css'
